channels:
  - conda-forge

dependencies:
  - python=3.9.16                 # https://pyreadiness.org/3.9
  - pip=22.1.2                    # https://pip.pypa.io/en/stable/news
  - pip:
    - rpaframework==23.5.2        # https://rpaframework.org/releasenotes.html
    - robocorp==0.4.0             # https://pypi.org/project/robocorp
    - robocorp-browser==1.0.2     # https://pypi.org/project/robocorp-browser
    - robocorp-http==0.2.0   
