[tool.robo]
name = "RPA Challenge 2"
description = "A simple example robot that solves the RPA Challenge"
python = "3.9.13"

[tool.robo.dependencies]
robocorp-tasks="0.1.6"
robocorp-browser="0.2.0"
robocorp-pdf="0.2.0"
robocorp-http="0.2.0"

[tool.robocorp.log]
log_filter_rules = [
    {name = "playwright", kind = "log_on_project_call"},
]
